### ISSUE TITLE
Broken Caption Button Height

### ISSUE THREAD

**Issue by IPTVmanreal** [Dulappy/aero-window-manager#1]
Trying to set the caption button height results in nothing happening, 

![image](https://github.com/Dulappy/aero-window-manager/assets/99894372/3b45f3f4-6e5e-4d47-9710-0094705a7f11)

OS Info:
Windows 10 22H2 Build 19045.4291
DWMBlurGlass
Windhawk
Aero Window Manager

**Comment by Dulappy** [comment]
What Windhawk mods are you using?

**Comment by IPTVmanreal** [comment]
> What Windhawk mods are you using?

Control Panel Reborn, DComp Unlocker, Disable the Windows 8+ OSD, Disk Pie Chart, DWM thick frames test, Explorer offset changer, Force thick frames PLUS, Remove UWP titlebars, Restore windows 7 network flyout, Windows 7 Clock Spacing, Acrylic Effect Radius Changer, Aerexplorer, Aero Flyout Fix, Aero Tray, Chrome UI Tweaks, Desktop Watermark Tweaks, Disable Feedback Hub Hotkey, Disable Immersive Context Menus, Disable Office Hotkeys, Dot Hide, Eradicate Immersive Menus, Fix Basic Caption Text, Legacy File Copy, Message Box Fix, Modernize Folder Picker Dialog, Notepad Clientedge, Old This PC Commands, Resource Redirect, UIRibbon Caption Icon Fix, Win32 Tray Clock Experience and Windows 7 Alt+Tab Loader

**Comment by Dulappy** [comment]
Disable all DWM-related mods (Should be DWM thick frames test, Force thick frames PLUS, and Acrylic Effect Radius Changer (I'm the author, this shouldn't affect anything, but better safe than sorry)). After that, restart DWM. If that doesn't work, upload a .reg file of your AWM registry keys located at `HKEY_LOCAL_MACHINE\SOFTWARE\AWM`.

**Comment by IPTVmanreal** [comment]
> Upload a .reg file of your AWM registry keys located at `HKEY_LOCAL_MACHINE\SOFTWARE\AWM`.

There's no registry key for AWM

![image](https://github.com/Dulappy/aero-window-manager/assets/99894372/ad44335e-c27c-4a43-94b7-b99c6abb3c08)

**Comment by Dulappy** [comment]
If you're able to modify any settings whatsoever, you have the aforementioned registry key. Even opening the GUI should create this key with default values inside. Are you sure you're looking in `HKEY_LOCAL_MACHINE` and not `HKEY_CURRENT_USER`?

**Comment by IPTVmanreal** [comment]
I'm looking in HKEY_LOCAL_MACHINE and I still can't find an AWM key

**Comment by Dulappy** [comment]
Alright, I figured it out. Change the "Titlebar Button Vertical Alignment" option to 0 (0 = Top, 1 = Center, 2 = Titlebar center, 3 = Bottom, 4 = Full).

**Comment by IPTVmanreal** [comment]
It worked
