### ISSUE TITLE
Getting stuck in "Listening for messages" in cmd prompt and dwm not launching

### ISSUE THREAD

**Issue by SebasMario** [Dulappy/aero-window-manager#11]
After doing the whole installation process and getting to when i input injector to c:\awm it skins the computer but does not open the cmd prompt and I am unable to edit any of the settings 
![image](https://github.com/Dulappy/aero-window-manager/assets/145221189/43967b46-8d14-4f9c-a59b-ab71a9435999)
![image](https://github.com/Dulappy/aero-window-manager/assets/145221189/1bae3df7-3d20-4d0d-adc5-7948287d17dc)

**Comment by Dulappy** [comment]
Yeah, I don't know why so many people are having this issue with values being set to 256... Perhaps I should bother Neptune about it.
