### ISSUE TITLE
How to undo the install process and uninstall AWM?

### ISSUE THREAD

**Issue by Asad-13** [Dulappy/aero-window-manager#12]
(Opening an issue because I couldn't find a discussions tab)

Okay, so the title is mostly self-explanatory. I followed the install process upto Step 5, after which I'm here.
![image](https://github.com/Dulappy/aero-window-manager/assets/87184327/eeaec187-fa36-44e8-8e23-412819a223a2)

Now I don't know what to do on that smaller SYSTEM cmd window, where it's waiting for an input. I can see transparency working on inactive windows, but not on active ones, and overall I'm just confused as to what I do here. The reason I'm so confused and haven't done anything at this point is because I've been in this position before, where I did something that I did not understand, after which undoing the changes made was a nightmare.

I'm slightly exaggerated when it comes to stuff like these; making sure anything I uninstall leaves absolutely no trace behind. The more undocumented things I do here, the harder it will be for me as layman to undo all of it. Kindly help me out and make a step-by-step guide on uninstalling AWM (Side note: funny coincidence how the name sounds like the sniper from PUBG)

**Comment by Dulappy** [comment]
Close the injector, end the dwm.exe process through Task Manager, type `regsvr32 /U C:\awm\msdia140_awm.dll` into a Command Prompt running as Administrator, delete all the AWM files, delete all the registry keys (which I see you have either done already, or haven't opened the configuration program at all).

**Comment by Asad-13** [comment]
> end the dwm.exe process through task manager

I don't explicitly a "dwm.exe", but I can see "Desktop Window Manager" under Windows processes that tells me that ending the task will cause Windowsnto be unusable and shut down. Is this the task I'm supposed to close or is it supposed to be something else? If I go ahead with this, Windows won't go corrupt or something, right?
