### ISSUE TITLE
Cannot Load Injection Library

### ISSUE THREAD

**Issue by nuclearwar1000** [Dulappy/aero-window-manager#13]
basically, after downloading pstools and running a cmd prompt thru psexec64 in the fashion stated in the readme, i get an error when trying to run injector that just states "error: cannot load injection library"
![error](https://github.com/user-attachments/assets/6b8fb0f0-74aa-43fb-9001-28615ac38100)

**Comment by Dulappy** [comment]
Do you have the MSVC 2019 runtime installed? It's mentioned at the very top of the installation instructions. It's not a step on its own because some people might already have it installed, but it is required for now.

**Comment by nuclearwar1000** [comment]
yea i do, i actually solved this by installing in older version of awm then reinstalling the latest lol. dunno what that was, maybe i originally screwed up registering the dll. although now my awm seems to not work on boot and i need to reinstall on restart

**Comment by Dulappy** [comment]
AWM loading itself on boot is not a feature. You're going to have to set up a task through Task Scheduler yourself in order to achieve that. Can you explain more about the second issue? What do you mean by needing to reinstall on restart?

**Comment by nuclearwar1000** [comment]
Hi! Yeah between these replies I set that up while kinda testing stuff out and it worked lol. I initially had a fairly poor grasp on how awm worked so I would keep re-registering and reinfecting the dlls lol, but everything is sorted now !

**Comment by Dulappy** [comment]
Ah, alright then, I'll close the issue.
