### ISSUE TITLE
How could i turn on "blur" on awm?

### ISSUE THREAD

**Issue by Tamim468** [Dulappy/aero-window-manager#2]
I have been waiting for awm to release and when it finally released, I set up a windows 10 22h2 virtual machine using vmware to try out awm but to find out the blur doesn't seem to be here at all. Videos and screenshots were sent a long time ago that shows awm being used which includes a working blur which I heard was called explorerblur because it's in explorer, like this one for example https://www.youtube.com/watch?v=KtMIytUqRac and this message in nostalgia project discord server https://discord.com/channels/1170481985664340112/1170481985664340115/1180590811986014248

What happened to it and If it is infact there, How could i use it since it doesn't seem to be properly documented? I am using aero10 msstyle.

Someone told me to set accentpolicy to 3 using awm config executable but that doesn't work either because it just says accentpolicy is out of range.

https://cdn.discordapp.com/attachments/1170482564243411055/1251902184254341130/20240616-1411-26.5847161.mp4?ex=66704443&is=666ef2c3&hm=b5bf5144d01edac48936fca92714644ef475d5cb30f66006e7da6728d5df0dc1&

![image](https://github.com/Dulappy/aero-window-manager/assets/79998020/b6121bc6-289f-4daf-bc3d-d276372773c4)

Unfortunately people just tell me to use dwmblurglass with awm at same time instead Wow..

**Comment by Dulappy** [comment]
Try setting AccentPolicy to 3 or 4 through the registry at `HKLM\SOFTWARE\AWM` if you really want to go down that route. Remember that the blur in AWM is not optimized in any way whatsoever, so dragging or resizing windows will be sluggish. My recommendation would be to use DWMBlurGlass or OpenGlass (which I haven't used personally). One thing to keep in mind when using AWM in combination with DWMBlurGlass is that the text is prone to disappear if DWMBG is launched after AWM, so the order in which these programs are run is important. Other than that, AWM should have no problem running alongside DWMBlurGlass.
