### ISSUE TITLE
AWM continuously crashes dwm.exe on latest Windows 10 (build 19045.5131) and kicks user back to logon screen

### ISSUE THREAD

**Issue by fireYtail** [Dulappy/aero-window-manager#27]
I have a desktop and a laptop computer. I had them running **on the previous Windows 10 update with the AWM injector without an issue**.

Today, **I updated both, and am forced to stop using the injector**. The screen continuously goes black and returns, dwm.exe crashes and restarts itself forever, it logs me out of my user account (sends me back to logon screen) and Windows is basically unusable with the injector after updating. I had to disable my injector auto-start scheduled task by booting from safe mode (because this broke my PC)

Windows 10 Pro build 19045.5131 (latest, you can see this number on "Settings --> System --> About")

**Comment by fireYtail** [comment]
So apparently deleting all the PDB files and running "regsvr32 c:\awm\msdia140_awm.dll" again fixes it. For anyone else that comes accross this problem, boot in safe mode if you had auto-launch like the Task Scheduler so you can stop it and boot normally again, then delete the PDB and re-register the msdia140 DLL. So far, looks like it's working... Scary to get stuck on logon screen with constant flickering though.

**Comment by megakarlach** [comment]
same thing happen here after recent update (LTSC 2021 19044.5608), it also managed to disable RTX 3060 driver aswell as windows think the graphics card have issues, running regsvr32 again fixes the issue.
