### ISSUE TITLE
Possible community page for regkey sets for specific themes?

### ISSUE THREAD

**Issue by IveMalfunctioned** [Dulappy/aero-window-manager#6]
It'd be cool to have community-made .reg key sets, to merge a specific set of values for a certain theme. Maybe on this GitHub, or on Discord somewhere

**Comment by IveMalfunctioned** [comment]
Also, how can we achieve the Aero theme?

**Comment by Dulappy** [comment]
I might create a Discord server. For now, play around with the settings.
