### ISSUE TITLE
DWM crashes on repeat with AWM on

### ISSUE THREAD

**Issue by TorutheRedFox** [Dulappy/aero-window-manager#8]
Running the injector from explorer does nothing and running it from the commandline will just make DWM crash on repeat every few seconds

**Comment by Dulappy** [comment]
Did you read the installation instructions?

Did you download the correct version of AWM for your system?

**Comment by TorutheRedFox** [comment]
oh wait i completely missed that part of the instructions i'm an idiot lmao
